export interface Employee {
    employeeid: string,
    title: string,
    nickname: string,
    name: string,
    gender: string,
    contact_no: string,
    personal_email: string,
    orgnazation_email: string,
    dob: string,
    emaergancy_no: string,
    blood_group: string,
    father_name: string,
    spouse_name: string,
    marital_status: string,
    reporting_manager_id: string,
    reporting_hr_id: string,
    employee_status: string,
    marriage_date: string,
    residentaial_status: string,
    place_of_birth: string,
    religioan: string,
    countryOfOrigin: string,
    internationalEmp: string,
    physicallyChallanged: string,
    remark: string,
    designation: any,
    department: any,
    employeeExperience: any,
    qualificationDetails: any,
    positionHistory: any,
    addressMaster: any,
    joiningDetails: any,
    identityDetails: any,
    employeeRelatedDocuments: any,
    dependent: any,
    bank: any,
    branch: any,
    role: any,
    doj: string,
    nationality: string,
    location:string,
    experienceLevel:string,
    action:string
}